### ISSUE TITLE
pyenet as a package

### ISSUE THREAD

**Issue by noway421** [feikname/spades-server#10]
One way or another, in order to build `spades-server` as a package, pyenet which is shipped alongside pysnip should be a package too. Either in the same source tree, or in different repo.

Mat^2 incorporated some changes in there so it wouldn't be possible to use upstream pyenet.

What could be a possible name for that package? `pyspades-pyenet`? `aos-pyenet`? `spades-server-pyenet`?

**Comment by feikname** [comment]
I vote for `pyspades-pyenet`.

**Comment by noway421** [comment]
Recent news: we keep it inside `pyspades` package for now as because only `pyspades` is using. the name is `enet`.

Further down the line it is even possible to merge pyenet to upstream (https://github.com/aresch/pyenet/issues/1)

**Comment by noway421** [comment]
Right now, we are shipping upstream copy pyenet which is patched during build time and enet is fetched. It is shipping "in the same source tree" as I've proposed in the original post.

The name chosen is `pyspades.enet` (it is a submodule) as proposed by swalladge.
