### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by noway421** [feikname/spades-server#5]
While PIP module might be too hard to tackle, a dockerfile wouldn't be hard to create. 

A usual combo of alpine and debian jessie is what hosted apps are going for these days.

**Comment by feikname** [comment]
I only heard about Docker, and read bit right now. It seems fine, I think it can be made in time for 0.1 and sure is waaay easier than providing a pip package.

**Comment by feikname** [comment]
See also: #8
